### ISSUE TITLE
do not quote $JAVA_ARGS here

### ISSUE THREAD

**Issue by peutch** [daniel-huss/migratedb#1]
Hi,

Here is the line responsible for this:
https://github.com/daniel-huss/migratedb/blob/38840f7d165a5c2e992bfc964a1b13b72a30df28/migratedb-commandline/src/main/assembly/migratedb#L39

Having an empty value for $JAVA_ARGS, it will generate a empty string for $1 to java command and it will then search for the wrong main class:
```
$ LANG=C ./migratedb 
Error: Could not find or load main class 
Caused by: java.lang.ClassNotFoundException: 
```

**Comment by daniel-huss** [comment]
Thank you very much for the report, I will get right to it.

**Comment by daniel-huss** [comment]
v1.0.0 has been released.
